  version: '3'

  services:
    web:
      build: .
      container_name: flask-gunicorn
      restart: always
      ports:
        - "${PORT}:${PORT}"
    nginx:
      image: nginx:1.17
      container_name: ngx-flask
      ports:
        - "80:80"
      volumes:
        - ./nginx:/etc/nginx/conf.d
        - ./app/static/:/static/
      depends_on:
        - web